### ISSUE TITLE
Slide Preview Miscolored

### ISSUE THREAD

**Issue by MasterTemple** [MasterTemple/CSCI-450-Group-Project#27]
When changing the color of the current presentation background, all the previews on the left (the saved songs) change their color as well. They should only change when we select apply all. The issue is that they are bound to the same variable, not the actual color value that is from their respective song object.

**Comment by Blueflier** [comment]
lets change:
* Changes are automatically applied to the current slide

to:
* Changes are automatically applied to all slides including previews
