### ISSUE TITLE
Error when exiting from the child window in presenter mode

### ISSUE THREAD

**Issue by MasterTemple** [MasterTemple/CSCI-450-Group-Project#28]
If you have 2 monitors and you are presenting, and you press escape while focused on the audience view (the one that just displays the lyrics), it will exit fullscreen. Press escape again and then it will close the child window and then take the window parent window back to the main screen. However, everything is empty. To fix this, you could probably just reload the page. Maybe you can just use `window.location.href = "/";`

**Comment by Blueflier** [comment]
I couldnt replicate the error?

**Comment by MasterTemple** [comment]
me neither lol
