### ISSUE TITLE
Find and Remove: Delete Whole Line

### ISSUE THREAD

**Issue by MasterTemple** [MasterTemple/CSCI-450-Group-Project#29]
When the entire contents of a line are deleted (with the exception of white space) in the remove `Remove Matches` option, remove the entire line if it is empty. Instead of just having a blank line.

**Comment by Blueflier** [comment]
I think this works fine?

**Comment by MasterTemple** [comment]
good call

**Comment by MasterTemple** [comment]
actually nevermind
