### ISSUE TITLE
Settings Sidebar Disappears When Closing

### ISSUE THREAD

**Issue by MasterTemple** [MasterTemple/CSCI-450-Group-Project#36]
## Opened

![image](https://github.com/MasterTemple/CSCI-450-Group-Project/assets/54373793/99458078-278a-4b3e-abd1-91e12796ea31)

## Closed

![image](https://github.com/MasterTemple/CSCI-450-Group-Project/assets/54373793/06377223-ecc6-489f-a7c8-1173c8d67b3e)

**Comment by Blueflier** [comment]
lets just get rid of this feature

**Comment by MasterTemple** [comment]
yes
