### ISSUE TITLE
Make Pretty: Action Button Relocation and Styling

### ISSUE THREAD

**Issue by MasterTemple** [MasterTemple/CSCI-450-Group-Project#38]
Style the unstyled buttons.
Relocate all the buttons into any configuration that is helpful and appealing.

![image](https://github.com/MasterTemple/CSCI-450-Group-Project/assets/54373793/71179ecd-1af6-4726-934a-0323b4a25b45)

**Comment by Blueflier** [comment]
Joseph is doing this
