### ISSUE TITLE
Search Song Doesn't Account For Capital Letters

### ISSUE THREAD

**Issue by joaquinllenado** [MasterTemple/CSCI-450-Group-Project#59]
"Known" shows up in songlist
![issue4](https://github.com/MasterTemple/CSCI-450-Group-Project/assets/124043232/092d5bfa-5f50-46a4-9cff-2f190289c4be)

"Known" doesn't show up on search
![issue5](https://github.com/MasterTemple/CSCI-450-Group-Project/assets/124043232/0620092b-b659-40df-996e-0ca2a3d95979)

**Comment by MasterTemple** [comment]
Fixed in https://github.com/MasterTemple/CSCI-450-Group-Project/pull/69
